name: experiments
favicon: null
layout_spectrum: 0.8822378693148494
typography_spectrum: 0.26419168058782816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8021754480432719
  lightness: 0.12241503642871976
  saturation: 0.9486156566999853
  rhythmicContrast: 0.9553932950366288
purpose: []
