name: experiments
favicon: null
layout_spectrum: 0.87205
typography_spectrum: 0.06912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edece7'
    - '#161209'
    - '#453924'
    - '#cfc7b3'
    - '#917f5c'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.9553932950366288
purpose: []
