name: experiments
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0704'
    - '#ebe2d3'
    - '#45341b'
    - '#c4a46c'
    - '#8f713e'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.9553932950366288
purpose: []
